import Head from 'next/head'
import Styled from 'styled-components'
import Header from '../component/Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <App> 
        <Header />
        </App>
       
      </body>
    </div>
  )
}

const App = Styled.div`
color: green
`
